### ISSUE TITLE
[Feature request] Support wildcards in -snippetpath args

### ISSUE THREAD

**Issue by srnagar** [jtulach/codesnippet4javadoc#15]
When configuring aggregate javadocs using codesnippet4javadoc in a multi-module maven project, I have to enumerate every sub-module's source path containing the code snippets as `-snippetpath` arg. 
For e.g.
```
<additionalOptions>
-snippetpath A/B/src/samples/java
-snippetpath C/D/src/samples/java
-snippetpath X/Y/src/samples/java
</additionalOptions>
```

It would be great if you can support wildcards to scan all sub-directories that match the regex. 

Something like this:
`<additionalOptions>-snippetpath **/src/samples/java</additionalOptions>`

**Comment by jtulach** [comment]
Good idea. I'd find it useful as well. Feel free to turn it into a PR.

**Comment by jtulach** [comment]
No pull request. No integration. No fun.
