### ISSUE TITLE
javadoc: error - Cannot read ./java/com/foo/doc-files/network-icon.png Input length = 1

### ISSUE THREAD

**Issue by singalen** [jtulach/codesnippet4javadoc#3]
I have images imbedded into my javadocs with: `<img src="doc-files/alert-diagram.png" alt="Alert diagram">`. It worked fine.

I added `codesnippet4javadoc` with:

	    -doclet org.apidesign.javadoc.codesnippet.Doclet \
	    -docletpath codesnippet4javadoc/doclet/target/classes \
	    -maxLineLength 120 \

Now I get the following errors in the log:

```
Loading source file java/com/foo/Matic.java...
Constructing Javadoc information...
javadoc: error - Cannot read ./java/com/foo/doc-files/alert-diagram.png Input length = 1
javadoc: error - Cannot read ./java/com/foo/doc-files/alert-icon.png Input length = 1
javadoc: error - Cannot read ./java/com/foo/doc-files/data-storage-diagram.png Input length = 1
javadoc: error - Cannot read ./java/com/foo/doc-files/data-storage-icon.png Input length = 1
Standard Doclet version 1.8.0_60
Building tree for all the packages and classes...
```

Without the doclet, this doesn't happen.

The images are still in the javadoc, so this is a cosmetic issue.

My software versions:

> codesnippet4javadoc: master (22728d5ef8c977554e29c917360e6cded5ea04c5)
> java version "1.8.0_60"
> Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
> Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
> OS X 10.11

**Comment by jtulach** [comment]
I haven't yet tried to combine the doclet with images. Thanks for the report.

**Comment by jtulach** [comment]
I think ddb6f12 fixes the problem. Can you please built from source and verify? If it works I can then release version `0.12`.

**Comment by singalen** [comment]
No errors now, thanks!
I get `warning - Skipping binary file ./java/com/foo/doc-files/alert-diagram.png` though.

**Comment by jtulach** [comment]
Yeah, I am afraid to suppress the warnings. They might mean something important and I am not sure what is the right way to check what files are binary and should be ignored. I hope the warnings are sufficient so far.

**Comment by jtulach** [comment]
I've just preformed the release process. It should be [available soon](http://repo1.maven.org/maven2/org/apidesign/javadoc/codesnippet-doclet/0.10/).
