### ISSUE TITLE
Don't use default system encoding for source files parsing

### ISSUE THREAD

**Issue by lcacheux** [jtulach/codesnippet4javadoc#9]
I work on a project with UTF-8 source code and a few code snippets parsed with this Doclet. Some of these snippets include UTF-8 special characters, but on systems with another encoding as default (ie ISO-8859-1), they are parsed as the default system encoding instead of the one configured for Javadoc.

The issue seems to come from the Snippets.scanDir method, where there is a call to `Charset.defaultCharset()`.

The charset used here should be the same as the "encoding" parameter passed to the javadoc command, or at least be configurable at the Doclet level.

**Comment by jtulach** [comment]
Thanks for using the doclet. Feel free to prepare a PR... I may look at it
too - later this week.
-jt


2018-05-30 14:20 GMT+02:00 Leo Cacheux <notifications@github.com>:

**Comment by lcacheux** [comment]
Fixed with https://github.com/jtulach/codesnippet4javadoc/pull/10
